In [36]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib

Using matplotlib backend: Qt5Agg

In [37]:
colnames = ['time', 'index', 'humidity', 'temp1','pressure','temp2', 'light_lvl']
data = pd.read_csv("logFile.csv",names=colnames, header=None)

In [38]:
data = data.set_index(['index'],drop=True)
data

           time  humidity  temp1   pressure  temp2  light_lvl
index
1       19:34:6     43.88  30.54  100957.50  29.87       1.13
2       19:34:6     42.96  30.62  100972.25  29.75       0.57
1       19:34:6     43.89  30.54  100959.50  29.87       1.12
2       19:34:6     42.92  30.64  100969.75  29.75       0.58
1       19:34:6     43.90  30.54  100958.75  29.87       1.12
2       19:34:6     42.91  30.63  100967.50  29.75       0.57
1       19:34:6     43.94  30.55  100959.25  29.87       1.12
2       19:34:7     42.91  30.64  100969.50  29.75       0.58
1       19:34:7     43.95  30.54  100955.50  29.87       1.12
2       19:34:8     42.87  30.62  100967.00  29.75       0.58
1       19:34:8     43.95  30.53  100959.00  29.87       1.12
2       19:34:8     42.82  30.63  100969.25  29.75       0.58
1       19:34:9     43.96  30.55  100955.50  29.87       1.12
2       19:34:9     42.79  30.62  100967.50  29.75       0.58
1      19:34:10     43.97  30.54  100959.50  29.87       1.12
2      19:34:11     42.80  30.61  100969.50  29.75       0.58
1      19:34:11     43.98  30.55  100956.00  29.87       1.12
2      19:34:12     42.81  30.62  100967.00  29.75       0.58
1      19:34:12     44.01  30.55  100959.50  29.87       1.12
2      19:34:13     42.80  30.63  100968.00  29.75       0.58
1      19:34:13     43.99  30.55  100956.75  29.87       1.12
2      19:34:14     42.77  30.63  100967.50  29.75       0.58
1      19:34:14     43.98  30.56  100960.50  29.87       1.12
2      19:34:15     42.76  30.63  100968.00  29.75       0.58
1      19:34:15     43.94  30.55  100955.50  29.87       1.11
2      19:34:16     42.74  30.61  100971.00  29.75       0.57
1      19:34:16     43.89  30.56  100957.25  29.87       1.10
2      19:34:17     42.72  30.63  100966.75  29.75       0.57
1      19:34:17     43.80  30.56  100957.00  29.87       1.10
2      19:34:18     42.71  30.63  100970.00  29.75       0.57
...         ...       ...    ...        ...    ...        ...
2      19:36:18     42.57  30.71  100969.75  29.81       0.56
1      19:36:18     43.12  30.69  100963.00  30.00       1.03
2      19:36:19     42.57  30.69  100968.50  29.81       0.56
1      19:36:19     43.09  30.69  100962.50  30.00       1.03
2      19:36:20     42.58  30.71  100971.25  29.81       0.56
1      19:36:20     43.09  30.69  100959.50  30.00       1.03
2      19:36:21     42.59  30.71  100970.50  29.81       0.55
1      19:36:21     43.08  30.69  100960.00  30.00       1.03
2      19:36:22     42.54  30.72  100970.00  29.81       0.55
1      19:36:22     43.08  30.69  100958.25  30.00       1.03
2      19:36:23     42.57  30.71  100973.00  29.81       0.55
1      19:36:23     43.06  30.70  100957.50  30.00       1.03
2      19:36:24     42.57  30.74  100967.75  29.81       0.55
1      19:36:24     43.10  30.68  100963.00  30.00       1.03
2      19:36:25     42.55  30.74  100970.00  29.81       0.55
1      19:36:25     43.17  30.68  100960.00  30.00       1.03
2      19:36:26     42.52  30.72  100971.00  29.81       0.56
1      19:36:26     43.20  30.68  100960.00  29.94       1.03
2      19:36:27     42.53  30.74  100971.75  29.81       0.56
1      19:36:27     43.21  30.69  100963.75  30.00       1.03
2      19:36:28     42.48  30.74  100968.75  29.81       0.55
1      19:36:28     43.22  30.69  100963.75  30.00       1.04
2      19:36:29     42.38  30.74  100968.50  29.81       0.55
1      19:36:29     43.22  30.69  100963.75  30.00       1.04
2      19:36:30     42.26  30.72  100968.75  29.81       0.57
1      19:36:30     43.16  30.70  100960.25  30.00       1.06
2      19:36:31     42.17  30.74  100967.50  29.81       0.57
1      19:36:31     43.06  30.69  100962.25  30.00       1.03
2      19:36:32     42.18  30.72  100967.25  29.81       0.58
1      19:36:32     43.05  30.68  100960.00  30.00       1.04

[299 rows x 6 columns]

In [39]:
sensor_1 = data.loc[data.index == 1]
sensor_2 = data.loc[data.index == 2]

In [40]:
new_index = [i for i in range(len(sensor_1.index))]
new_index2 = [i for i in range(len(sensor_2.index))]

In [41]:
sensor_1['new_index'] = new_index
sensor_2['new_index'] = new_index2

/home/yahgo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/home/yahgo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [42]:
#sensor_1 = sensor_1.set_index(['new_index'], drop = True)

sensor_1['time'] = pd.to_datetime(sensor_1['time'], format='%H:%M:%S')
sensor_1.set_index('time', inplace=True)
sensor_2['time'] = pd.to_datetime(sensor_2['time'], format='%H:%M:%S')
sensor_2.set_index('time', inplace=True)

/home/yahgo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/yahgo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [45]:
sensor_1['humidity'].plot()